### ISSUE TITLE
Missing styles on the account and cart dropdowns when we are on a 404 page

### ISSUE THREAD

**Issue by sujith-corra** [hlxsites/aem-boilerplate-commerce#147]
We observed that the styles for the account and cart dropdowns are missing when redirected to a 404 page from the PDP (e.g., https://develop--aem-boilerplate-commerce--hlxsites.aem.live/products/sss-s). Even after including the drop-in modules in the 404.html file, the issue persists.
![account dropdown](https://github.com/user-attachments/assets/0f616f4f-7709-485c-b68a-6bfb6946667e)
![minicart](https://github.com/user-attachments/assets/c37df840-c831-402f-b1ba-490a4fd4ddf1)

**Comment by sirugh** [comment]
Thanks for reporting this! Appreciate the repro as well.

**Comment by sirugh** [comment]
Resolved in #236
